package com.hex.chattie.network.responses

data class Preferences(
    val audioNotifications: String,
    val autoImageLoad: Boolean,
    val collapseMediaByDefault: Boolean,
    val convertAsciiEmoji: Boolean,
    val desktopNotificationRequireInteraction: Boolean,
    val desktopNotifications: String,
    val displayAvatars: Boolean,
    val emailNotificationMode: String,
    val enableAutoAway: Boolean,
    val enableMessageParserEarlyAdoption: Boolean,
    val hideFlexTab: Boolean,
    val hideRoles: Boolean,
    val hideUsernames: Boolean,
    val idleTimeLimit: Int,
    val messageViewMode: Int,
    val mobileNotifications: String,
    val muteFocusedConversations: Boolean,
    val newMessageNotification: String,
    val newRoomNotification: String,
    val notificationsSoundVolume: Int,
    val saveMobileBandwidth: Boolean,
    val sendOnEnter: String,
    val showMessageInMainThread: Boolean,
    val sidebarDisplayAvatar: Boolean,
    val sidebarGroupByType: Boolean,
    val sidebarShowFavorites: Boolean,
    val sidebarShowUnread: Boolean,
    val sidebarSortby: String,
    val sidebarViewMode: String,
    val unreadAlert: Boolean,
    val useEmojis: Boolean
)